### PR TITLE
Update Users Guide

### PR DESCRIPTION
**Pull request by j-derrico**
**Description**
Fixes Issue #177, Updating the UW Tools users guide 
**Type of change**

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

**Checklist**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes need updates to the documentation.  I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [x] Any dependent changes have been merged and published

### CODE REVIEW

**Review by christinaholtNOAA — APPROVED** [review]
@j-derrico This looks great! Thank you!

I built the docs locally and looked around in the browser. I didn't see any failures, and I can't seem to see why the github check failed. Do you have any ideas.

If we can't spot that with fresh eyes later, maybe we just merge it and see if perhaps it is a permissions issue or something similar? 

The content looks good.

**Comment by WeirAE** [comment]
Odd, it does build ok for me too, and technically it does say 'build successful' before it fails. I'll have to recheck with fresh eyes. There are several warnings on small formatting things but I'd be surprised if that was it. The first part reads a little ChatGPT-y, but its good!

**Comment by j-derrico** [comment]
Is it possible to log in to readthedocs and see what happens when it builds from that side?

**Comment by christinaholtNOAA** [comment]
I think the failure is likely related to this chunk of code in jobs/build_documentation.sh.

```
warning_file=${DOCS_DIR}/_build/warnings.log
if [ -s $warning_file ]; then
  cp -r ${DOCS_DIR}/_build/warnings.log artifact/doc_warnings.log
  cp artifact/doc_warnings.log artifact/documentation
  exit 1
fi
```

It seems like we aren't tolerating anything in the warnings file.

**Comment by WeirAE** [comment]
Ah, so it was the warnings - it looked like mostly indent and label complaints, I think thats fixable

**Review by christinaholtNOAA — APPROVED** [review]

**Pull request merged**
