### PR TITLE
UW-208: As a user, I'd like to see uniform logging for the ins/outs of a whole variety of functions/methods (V2)

### PR DESCRIPTION
**Pull request by WeirAE**
**Description**

Given: the user provides a debug flag to any logger-enabled tool
When: a logger decorator function has been applied to a called method
Then: information about the caller, local variables, and expected output will be printed to the screen and log file
Completes issue #165 
Previous PRs #174  , #176 , #188 

**Type of change**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

- [x] pytests in GitHub actions.
- [x] Tests on Ubuntu OS

**Checklist**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation.  I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

### CODE REVIEW

**Comment by WeirAE** [comment]
Double-checked that this was the correct edit version and should be good to go!

**Comment by christinaholtNOAA** [comment]
Please do address the failing linter and address the comments I last left on the previous PR that needed to be closed.

**Comment by WeirAE** [comment]
> Please do address the failing linter and address the comments I last left on the previous PR that needed to be closed.

Ah, there was one residual error - still weird when the VS Code linter lets me get away with that. I've also made changes to allow for user logfile override and the test uses PID so there should be no errors. If this works, I'll fix #196 with that

**Comment by WeirAE** [comment]
@christinaholtNOAA I've added a direct return, but I'd really prefer to make it an attribute of the function. Unfortunately, since its not a class I'm struggling a bit on the syntax

**Pull request closed without merging**
