### PR TITLE
Add better error handling.

### PR DESCRIPTION
**Pull request by christinaholtNOAA**
**Description**

Some error handling found during the acceptance testing process was less than fabulous. This is an attempt to do it better for users calling UW Tools via the command line, and also to provide an example of how error handling can be done by Applications that will integrate the tool via Python.

In this example, we catch the specific pyyaml error where it happens, but raise a generic `UWConfigError` so that we can catch it at the highest level (the caller) and exit the program with a descriptive error. By taking this approach, the integration into a different Python interface will still be able to handle an exception raised by the uwtools package, and handle it however it wants. Our script, `set_config.py`, chooses to handle it by calling a `sys.exit()` with the original error.

**Type of change**

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

I've run the set_config.py tool by hand on the command line using SRW config files as input. Specifically:

```
./scripts/set_config.py -i ${SRW_APP}/ush/config_defaults.yaml -c ${SRW_APP}/ush/config.community.yaml -d -v
```
Where `SRW_APP` is the path to my clone of a recent version of SRW App.

This should trigger a `yaml.constructor.ConstructorError` when reading the config_default.yaml file.

**Checklist**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation.  I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

### CODE REVIEW

**Comment by christinaholtNOAA** [comment]
@venitahagerty Do you mind taking a look here and see if this is getting closer to the behavior you'd expect?

**Comment by venitahagerty** [comment]
Yes, much better error messaging.

ERROR:
The input config file contains a constructor
that is not registered with the uwtools package.

constructor: '!nowtimestamp'
config file: /Users/venita.hagerty/uw/samples/update_config_defaults.yaml

Please define the constructor before proceeding.

**Review by venitahagerty — APPROVED** [review]
LGTM

**Comment by christinaholtNOAA** [comment]
Thanks @venitahagerty. I'll try to get similar messages in for handling a situation where a Jinja2 filter isn't defined. I'm not sure how painful that might be.

**Comment by venitahagerty** [comment]
I added an incorrect Jinja2 filter to two entries in my update yaml file (pipe_join, not path_join). I updated the config_defaults.yaml file. I received an error for the first incorrect Jinja2 filter.

grep pipe_join samples/update_config_defaults3.yaml
  CUSTOM_POST_CONFIG_FP: '{{ [user.PARMdir, FV3_NML_YAML_CONFIG_FN]|pipe_join }}'
  FV3_NML_ENSMEM_FPS: '{% for mem in ENSMEM_NAMES %}{{ [EXPTDIR, "%s_%s" % FV3_NML_FN, mem]|pipe_join }}{% endfor %}'

Exception: No filter named 'pipe_join'.

ERROR:
The input config file contains a Jinja2 filter
that is not registered with the uwtools package.

filter: 'pipe_join'
key: CUSTOM_POST_CONFIG_FP

Define the filter before proceeding.
Traceback (most recent call last):
  File "/scratch1/BMC/zrtrr/uw/workflow-tools/src/uwtools/config.py", line 245, in dereference
    j2tmpl = J2Template(configure_obj=config_obj,
  File "/scratch1/BMC/zrtrr/uw/workflow-tools/src/uwtools/j2template.py", line 93, in __init__
    self.template = self._load_string(template_str)
  File "/scratch1/BMC/zrtrr/uw/workflow-tools/src/uwtools/logger.py", line 178, in log_decorator_wrapper
    value = func(self, *args, **kwargs)
  File "/scratch1/BMC/zrtrr/uw/workflow-tools/src/uwtools/j2template.py", line 143, in _load_string
    return self._j2env.from_string(template_str)
  File "/home/role.rtrr/.local/lib/python3.9/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/role.rtrr/.local/lib/python3.9/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/role.rtrr/.local/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateAssertionError: No filter named 'pipe_join'.

ERROR:
The input config file contains a Jinja2 filter
that is not registered with the uwtools package.

filter: 'pipe_join'
key: CUSTOM_POST_CONFIG_FP

Define the filter before proceeding.

**Comment by christinaholtNOAA** [comment]
@venitahagerty Do you think we need to report all instances up front, or would it be acceptable at this point, to just have it fail on the first one, knowing that you may need to work through one error at a time?

**Comment by venitahagerty** [comment]
I would probably find that annoying in production, but I could go either way now.

**Review by venitahagerty — APPROVED** [review]
LGTM

**Comment by christinaholtNOAA** [comment]
Let's maybe see how annoying it gets when integrating into Apps, and maybe use that to drive a more robust error handling for the full file.

**Pull request merged**
